on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.37
      with:
        github_token: ${{ secrets.GO_TOKEN }}
        goos: linux
        goarch: ${{ matrix.goarch }}
        extra_files: README.md
